class InputDomain:
    def __init__(self, driver):
        self.driver = driver

    def dispatchDragEvent(self, type_, x, y, data, modifiers=None):
        """
        Dispatches a drag event into the page.
        - type (string): Type of the drag event.
        - x (number): X coordinate of the event relative to the main frame's viewport in CSS pixels.
        - y (number): Y coordinate of the event relative to the main frame's viewport in CSS pixels. 0 refers to
the top of the viewport and Y increases as it proceeds towards the bottom of the viewport.
        - data (any): 
        - modifiers (integer): Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
(default: 0).
        """
        params = {}
        params["type"] = type_
        params["x"] = x
        params["y"] = y
        params["data"] = data
        if modifiers is not None:
            params["modifiers"] = modifiers
        return self.driver.execute_and_wait("Input.dispatchDragEvent", params)

    def dispatchKeyEvent(self, type_, modifiers=None, timestamp=None, text=None, unmodifiedText=None, keyIdentifier=None, code=None, key=None, windowsVirtualKeyCode=None, nativeVirtualKeyCode=None, autoRepeat=None, isKeypad=None, isSystemKey=None, location=None, commands=None):
        """
        Dispatches a key event to the page.
        - type (string): Type of the key event.
        - modifiers (integer): Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
(default: 0).
        - timestamp (any): Time at which the event occurred.
        - text (string): Text as generated by processing a virtual key code with a keyboard layout. Not needed for
for `keyUp` and `rawKeyDown` events (default: "")
        - unmodifiedText (string): Text that would have been generated by the keyboard if no modifiers were pressed (except for
shift). Useful for shortcut (accelerator) key handling (default: "").
        - keyIdentifier (string): Unique key identifier (e.g., 'U+0041') (default: "").
        - code (string): Unique DOM defined string value for each physical key (e.g., 'KeyA') (default: "").
        - key (string): Unique DOM defined string value describing the meaning of the key in the context of active
modifiers, keyboard layout, etc (e.g., 'AltGr') (default: "").
        - windowsVirtualKeyCode (integer): Windows virtual key code (default: 0).
        - nativeVirtualKeyCode (integer): Native virtual key code (default: 0).
        - autoRepeat (boolean): Whether the event was generated from auto repeat (default: false).
        - isKeypad (boolean): Whether the event was generated from the keypad (default: false).
        - isSystemKey (boolean): Whether the event was a system key event (default: false).
        - location (integer): Whether the event was from the left or right side of the keyboard. 1=Left, 2=Right (default:
0).
        - commands (array): Editing commands to send with the key event (e.g., 'selectAll') (default: []).
These are related to but not equal the command names used in `document.execCommand` and NSStandardKeyBindingResponding.
See https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/editing/commands/editor_command_names.h for valid command names.
        """
        params = {}
        params["type"] = type_
        if modifiers is not None:
            params["modifiers"] = modifiers
        if timestamp is not None:
            params["timestamp"] = timestamp
        if text is not None:
            params["text"] = text
        if unmodifiedText is not None:
            params["unmodifiedText"] = unmodifiedText
        if keyIdentifier is not None:
            params["keyIdentifier"] = keyIdentifier
        if code is not None:
            params["code"] = code
        if key is not None:
            params["key"] = key
        if windowsVirtualKeyCode is not None:
            params["windowsVirtualKeyCode"] = windowsVirtualKeyCode
        if nativeVirtualKeyCode is not None:
            params["nativeVirtualKeyCode"] = nativeVirtualKeyCode
        if autoRepeat is not None:
            params["autoRepeat"] = autoRepeat
        if isKeypad is not None:
            params["isKeypad"] = isKeypad
        if isSystemKey is not None:
            params["isSystemKey"] = isSystemKey
        if location is not None:
            params["location"] = location
        if commands is not None:
            params["commands"] = commands
        return self.driver.execute_and_wait("Input.dispatchKeyEvent", params)

    def insertText(self, text):
        """
        This method emulates inserting text that doesn't come from a key press, for example an emoji keyboard or an IME.
        - text (string): The text to insert.
        """
        params = {}
        params["text"] = text
        return self.driver.execute_and_wait("Input.insertText", params)

    def imeSetComposition(self, text, selectionStart, selectionEnd, replacementStart=None, replacementEnd=None):
        """
        This method sets the current candidate text for IME. Use imeCommitComposition to commit the final text. Use imeSetComposition with empty string as text to cancel composition.
        - text (string): The text to insert
        - selectionStart (integer): selection start
        - selectionEnd (integer): selection end
        - replacementStart (integer): replacement start
        - replacementEnd (integer): replacement end
        """
        params = {}
        params["text"] = text
        params["selectionStart"] = selectionStart
        params["selectionEnd"] = selectionEnd
        if replacementStart is not None:
            params["replacementStart"] = replacementStart
        if replacementEnd is not None:
            params["replacementEnd"] = replacementEnd
        return self.driver.execute_and_wait("Input.imeSetComposition", params)

    def dispatchMouseEvent(self, type_, x, y, modifiers=None, timestamp=None, button=None, buttons=None, clickCount=None, force=None, tangentialPressure=None, tiltX=None, tiltY=None, twist=None, deltaX=None, deltaY=None, pointerType=None):
        """
        Dispatches a mouse event to the page.
        - type (string): Type of the mouse event.
        - x (number): X coordinate of the event relative to the main frame's viewport in CSS pixels.
        - y (number): Y coordinate of the event relative to the main frame's viewport in CSS pixels. 0 refers to
the top of the viewport and Y increases as it proceeds towards the bottom of the viewport.
        - modifiers (integer): Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
(default: 0).
        - timestamp (any): Time at which the event occurred.
        - button (any): Mouse button (default: "none").
        - buttons (integer): A number indicating which buttons are pressed on the mouse when a mouse event is triggered.
Left=1, Right=2, Middle=4, Back=8, Forward=16, None=0.
        - clickCount (integer): Number of times the mouse button was clicked (default: 0).
        - force (number): The normalized pressure, which has a range of [0,1] (default: 0).
        - tangentialPressure (number): The normalized tangential pressure, which has a range of [-1,1] (default: 0).
        - tiltX (number): The plane angle between the Y-Z plane and the plane containing both the stylus axis and the Y axis, in degrees of the range [-90,90], a positive tiltX is to the right (default: 0).
        - tiltY (number): The plane angle between the X-Z plane and the plane containing both the stylus axis and the X axis, in degrees of the range [-90,90], a positive tiltY is towards the user (default: 0).
        - twist (integer): The clockwise rotation of a pen stylus around its own major axis, in degrees in the range [0,359] (default: 0).
        - deltaX (number): X delta in CSS pixels for mouse wheel event (default: 0).
        - deltaY (number): Y delta in CSS pixels for mouse wheel event (default: 0).
        - pointerType (string): Pointer type (default: "mouse").
        """
        params = {}
        params["type"] = type_
        params["x"] = x
        params["y"] = y
        if modifiers is not None:
            params["modifiers"] = modifiers
        if timestamp is not None:
            params["timestamp"] = timestamp
        if button is not None:
            params["button"] = button
        if buttons is not None:
            params["buttons"] = buttons
        if clickCount is not None:
            params["clickCount"] = clickCount
        if force is not None:
            params["force"] = force
        if tangentialPressure is not None:
            params["tangentialPressure"] = tangentialPressure
        if tiltX is not None:
            params["tiltX"] = tiltX
        if tiltY is not None:
            params["tiltY"] = tiltY
        if twist is not None:
            params["twist"] = twist
        if deltaX is not None:
            params["deltaX"] = deltaX
        if deltaY is not None:
            params["deltaY"] = deltaY
        if pointerType is not None:
            params["pointerType"] = pointerType
        return self.driver.execute_and_wait("Input.dispatchMouseEvent", params)

    def dispatchTouchEvent(self, type_, touchPoints, modifiers=None, timestamp=None):
        """
        Dispatches a touch event to the page.
        - type (string): Type of the touch event. TouchEnd and TouchCancel must not contain any touch points, while
TouchStart and TouchMove must contains at least one.
        - touchPoints (array): Active touch points on the touch device. One event per any changed point (compared to
previous touch event in a sequence) is generated, emulating pressing/moving/releasing points
one by one.
        - modifiers (integer): Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
(default: 0).
        - timestamp (any): Time at which the event occurred.
        """
        params = {}
        params["type"] = type_
        params["touchPoints"] = touchPoints
        if modifiers is not None:
            params["modifiers"] = modifiers
        if timestamp is not None:
            params["timestamp"] = timestamp
        return self.driver.execute_and_wait("Input.dispatchTouchEvent", params)

    def cancelDragging(self):
        """
        Cancels any active dragging in the page.
        """
        params = {}
        return self.driver.execute_and_wait("Input.cancelDragging", params)

    def emulateTouchFromMouseEvent(self, type_, x, y, button, timestamp=None, deltaX=None, deltaY=None, modifiers=None, clickCount=None):
        """
        Emulates touch event from the mouse event parameters.
        - type (string): Type of the mouse event.
        - x (integer): X coordinate of the mouse pointer in DIP.
        - y (integer): Y coordinate of the mouse pointer in DIP.
        - button (any): Mouse button. Only "none", "left", "right" are supported.
        - timestamp (any): Time at which the event occurred (default: current time).
        - deltaX (number): X delta in DIP for mouse wheel event (default: 0).
        - deltaY (number): Y delta in DIP for mouse wheel event (default: 0).
        - modifiers (integer): Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
(default: 0).
        - clickCount (integer): Number of times the mouse button was clicked (default: 0).
        """
        params = {}
        params["type"] = type_
        params["x"] = x
        params["y"] = y
        params["button"] = button
        if timestamp is not None:
            params["timestamp"] = timestamp
        if deltaX is not None:
            params["deltaX"] = deltaX
        if deltaY is not None:
            params["deltaY"] = deltaY
        if modifiers is not None:
            params["modifiers"] = modifiers
        if clickCount is not None:
            params["clickCount"] = clickCount
        return self.driver.execute_and_wait("Input.emulateTouchFromMouseEvent", params)

    def setIgnoreInputEvents(self, ignore):
        """
        Ignores input events (useful while auditing page).
        - ignore (boolean): Ignores input events processing when set to true.
        """
        params = {}
        params["ignore"] = ignore
        return self.driver.execute_and_wait("Input.setIgnoreInputEvents", params)

    def setInterceptDrags(self, enabled):
        """
        Prevents default drag and drop behavior and instead emits `Input.dragIntercepted` events. Drag and drop behavior can be directly controlled via `Input.dispatchDragEvent`.
        - enabled (boolean): 
        """
        params = {}
        params["enabled"] = enabled
        return self.driver.execute_and_wait("Input.setInterceptDrags", params)

    def synthesizePinchGesture(self, x, y, scaleFactor, relativeSpeed=None, gestureSourceType=None):
        """
        Synthesizes a pinch gesture over a time period by issuing appropriate touch events.
        - x (number): X coordinate of the start of the gesture in CSS pixels.
        - y (number): Y coordinate of the start of the gesture in CSS pixels.
        - scaleFactor (number): Relative scale factor after zooming (>1.0 zooms in, <1.0 zooms out).
        - relativeSpeed (integer): Relative pointer speed in pixels per second (default: 800).
        - gestureSourceType (any): Which type of input events to be generated (default: 'default', which queries the platform
for the preferred input type).
        """
        params = {}
        params["x"] = x
        params["y"] = y
        params["scaleFactor"] = scaleFactor
        if relativeSpeed is not None:
            params["relativeSpeed"] = relativeSpeed
        if gestureSourceType is not None:
            params["gestureSourceType"] = gestureSourceType
        return self.driver.execute_and_wait("Input.synthesizePinchGesture", params)

    def synthesizeScrollGesture(self, x, y, xDistance=None, yDistance=None, xOverscroll=None, yOverscroll=None, preventFling=None, speed=None, gestureSourceType=None, repeatCount=None, repeatDelayMs=None, interactionMarkerName=None):
        """
        Synthesizes a scroll gesture over a time period by issuing appropriate touch events.
        - x (number): X coordinate of the start of the gesture in CSS pixels.
        - y (number): Y coordinate of the start of the gesture in CSS pixels.
        - xDistance (number): The distance to scroll along the X axis (positive to scroll left).
        - yDistance (number): The distance to scroll along the Y axis (positive to scroll up).
        - xOverscroll (number): The number of additional pixels to scroll back along the X axis, in addition to the given
distance.
        - yOverscroll (number): The number of additional pixels to scroll back along the Y axis, in addition to the given
distance.
        - preventFling (boolean): Prevent fling (default: true).
        - speed (integer): Swipe speed in pixels per second (default: 800).
        - gestureSourceType (any): Which type of input events to be generated (default: 'default', which queries the platform
for the preferred input type).
        - repeatCount (integer): The number of times to repeat the gesture (default: 0).
        - repeatDelayMs (integer): The number of milliseconds delay between each repeat. (default: 250).
        - interactionMarkerName (string): The name of the interaction markers to generate, if not empty (default: "").
        """
        params = {}
        params["x"] = x
        params["y"] = y
        if xDistance is not None:
            params["xDistance"] = xDistance
        if yDistance is not None:
            params["yDistance"] = yDistance
        if xOverscroll is not None:
            params["xOverscroll"] = xOverscroll
        if yOverscroll is not None:
            params["yOverscroll"] = yOverscroll
        if preventFling is not None:
            params["preventFling"] = preventFling
        if speed is not None:
            params["speed"] = speed
        if gestureSourceType is not None:
            params["gestureSourceType"] = gestureSourceType
        if repeatCount is not None:
            params["repeatCount"] = repeatCount
        if repeatDelayMs is not None:
            params["repeatDelayMs"] = repeatDelayMs
        if interactionMarkerName is not None:
            params["interactionMarkerName"] = interactionMarkerName
        return self.driver.execute_and_wait("Input.synthesizeScrollGesture", params)

    def synthesizeTapGesture(self, x, y, duration=None, tapCount=None, gestureSourceType=None):
        """
        Synthesizes a tap gesture over a time period by issuing appropriate touch events.
        - x (number): X coordinate of the start of the gesture in CSS pixels.
        - y (number): Y coordinate of the start of the gesture in CSS pixels.
        - duration (integer): Duration between touchdown and touchup events in ms (default: 50).
        - tapCount (integer): Number of times to perform the tap (e.g. 2 for double tap, default: 1).
        - gestureSourceType (any): Which type of input events to be generated (default: 'default', which queries the platform
for the preferred input type).
        """
        params = {}
        params["x"] = x
        params["y"] = y
        if duration is not None:
            params["duration"] = duration
        if tapCount is not None:
            params["tapCount"] = tapCount
        if gestureSourceType is not None:
            params["gestureSourceType"] = gestureSourceType
        return self.driver.execute_and_wait("Input.synthesizeTapGesture", params)

